//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int ClaimID { get; set; }
        public int UserPolicyID { get; set; }
        public System.DateTime ClaimDate { get; set; }
        public string ClaimType { get; set; }
        public string Reason { get; set; }
        public decimal ClaimedAmount { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<System.DateTime> DecisionAt { get; set; }
    
        public virtual UserPolicy UserPolicy { get; set; }
    }
}
